# Generated by Django 5.2.11 on 2026-02-28 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_gymadminlink'),
        ('users', '0003_userfitnessprofile_favoritegym'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritegym',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoritegym',
            name='gym_name',
            field=models.CharField(blank=True, help_text='For AI-generated gyms not in DB', max_length=255),
        ),
        migrations.AlterField(
            model_name='favoritegym',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='gyms.gym'),
        ),
    ]
