# Generated by Django 5.2.11 on 2026-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_favoritegym_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymbooking',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="User's GPS location at check-in", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='gymbooking',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="User's GPS location at check-in", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='gymbooking',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user checked in', null=True),
        ),
        migrations.AddField(
            model_name='gymbooking',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user checked out', null=True),
        ),
        migrations.AddField(
            model_name='gymbooking',
            name='session_duration',
            field=models.DurationField(blank=True, help_text='Duration of gym session', null=True),
        ),
        migrations.AlterField(
            model_name='gymbooking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked In'), ('completed', 'Completed')], default='booked', max_length=20),
        ),
    ]
