# Generated by Django 5.2.11 on 2026-03-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_gymbooking_check_in_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfitnessprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='profile_photos/'),
        ),
    ]
