services:
  - type: web
    name: allflex
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn allflex.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_MODE
        value: mongodb
      - key: PYTHON_VERSION
        value: 3.11.0
