# Generated by Django 5.2.3 on 2025-06-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='gym',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
