# Generated by Django 5.2.11 on 2026-02-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_creditpack_usercreditpack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditpack',
            options={'ordering': ['tier', 'price'], 'verbose_name': 'Credit Pack', 'verbose_name_plural': 'Credit Packs'},
        ),
    ]
