# Generated by Django 5.2.11 on 2026-02-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_alter_creditpack_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='is_verified_partner',
            field=models.BooleanField(default=True, help_text='Official ALLFLEX partner gym'),
        ),
    ]
