# Generated by Django 5.2.11 on 2026-02-24 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_gym_is_verified_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymOwnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(help_text='Gym name from search', max_length=255)),
                ('gym_address', models.CharField(help_text='Full address from search', max_length=500)),
                ('owner_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('years_in_business', models.IntegerField()),
                ('total_members', models.IntegerField()),
                ('has_ac', models.BooleanField(default=False, verbose_name='Air Conditioning')),
                ('has_changing_rooms', models.BooleanField(default=False, verbose_name='Changing/Dressing Rooms')),
                ('has_showers', models.BooleanField(default=False, verbose_name='Showers/Washrooms')),
                ('has_lockers', models.BooleanField(default=False, verbose_name='Lockers')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Parking Facility')),
                ('has_trainers', models.BooleanField(default=False, verbose_name='Personal Trainers')),
                ('has_cardio', models.BooleanField(default=False, verbose_name='Cardio Equipment')),
                ('has_weights', models.BooleanField(default=False, verbose_name='Free Weights')),
                ('has_machines', models.BooleanField(default=False, verbose_name='Weight Machines')),
                ('has_group_classes', models.BooleanField(default=False, verbose_name='Group Fitness Classes')),
                ('has_spa', models.BooleanField(default=False, verbose_name='Spa/Sauna/Steam Room')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Swimming Pool')),
                ('has_cafeteria', models.BooleanField(default=False, verbose_name='Cafeteria/Juice Bar')),
                ('has_music', models.BooleanField(default=False, verbose_name='Music System')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('business_proof', models.FileField(blank=True, null=True, upload_to='gym_requests/')),
                ('additional_info', models.TextField(blank=True)),
                ('ai_recommendation', models.TextField(blank=True, help_text='AI analysis and recommendation')),
                ('suggested_tier', models.IntegerField(blank=True, choices=[(1, 'Tier 1 - Basic'), (2, 'Tier 2 - Standard'), (3, 'Tier 3 - Premium'), (4, 'Tier 4 - Elite')], null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gym Owner Request',
                'verbose_name_plural': 'Gym Owner Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
