# Generated by Django 5.2.11 on 2026-02-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_gymownerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymownerrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='gymownerrequest',
            name='user_id',
            field=models.CharField(default='unknown', help_text='User ID (MongoDB ObjectId or SQL integer)', max_length=100),
        ),
        migrations.AddField(
            model_name='gymownerrequest',
            name='username',
            field=models.CharField(default='unknown', help_text='Username for display', max_length=150),
        ),
    ]
