# Generated by Django 5.2.11 on 2026-02-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_remove_gymownerrequest_user_gymownerrequest_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymAdminLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Gym',
                'verbose_name_plural': 'Gyms',
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
