"""
Django settings for allflex project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-your-default-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# ALLOWED_HOSTS configuration
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# Automatically add Render domain if deployed on Render
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Add *.onrender.com domains (Render deployment)
if not DEBUG or os.getenv('RENDER'):
    ALLOWED_HOSTS.extend([
        '.onrender.com',
        'allflex.onrender.com',
    ])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'accounts',
    'gyms',
    'users',
    'adminpanel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'accounts.middleware.MongoAuthenticationMiddleware',  # Custom middleware for MongoDB support
    'accounts.admin_middleware.AdminSessionMiddleware',  # Handle admin/MongoDB session conflicts
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'allflex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'theme' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'allflex.context_processors.user_profile_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'allflex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# MongoDB or SQLite configuration based on DATABASE_MODE env var
DATABASE_MODE = os.getenv('DATABASE_MODE', 'sqlite').lower()

if DATABASE_MODE == 'mongodb':
    # MongoDB Configuration (using MongoEngine)
    import mongoengine
    
    MONGO_DB_NAME = os.getenv('MONGO_DB_NAME', 'allflex_db')
    MONGO_DB_USER = os.getenv('MONGO_DB_USER', '')
    MONGO_DB_PASSWORD = os.getenv('MONGO_DB_PASSWORD', '')
    MONGO_DB_HOST = os.getenv('MONGO_DB_HOST', '')
    
    # Build MongoDB connection string for Atlas
    if MONGO_DB_USER and MONGO_DB_PASSWORD and MONGO_DB_HOST:
        MONGODB_CONNECTION_STRING = (
            f"mongodb+srv://{MONGO_DB_USER}:{MONGO_DB_PASSWORD}@{MONGO_DB_HOST}/"
            f"{MONGO_DB_NAME}?retryWrites=true&w=majority&appName=AllFlex"
        )
    else:
        # Fallback for local MongoDB
        MONGODB_CONNECTION_STRING = f"mongodb://localhost:27017/{MONGO_DB_NAME}"
    
    # Connect to MongoDB using MongoEngine
    try:
        mongoengine.connect(
            db=MONGO_DB_NAME,
            host=MONGODB_CONNECTION_STRING,
            alias='default',
            maxPoolSize=50,
            minPoolSize=10,
            serverSelectionTimeoutMS=5000,
            connectTimeoutMS=10000,
            socketTimeoutMS=10000,
        )
        print(f"[OK] Connected to MongoDB: {MONGO_DB_NAME}")
    except Exception as e:
        print(f"[ERROR] MongoDB connection failed: {e}")
        print("[WARNING] Check your .env file and MongoDB Atlas setup")
    
    # Django still needs a dummy database for contrib apps (admin, sessions, etc.)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db_dummy.sqlite3',
        }
    }
    
    # Use custom authentication backend for MongoDB
    AUTHENTICATION_BACKENDS = [
        'accounts.auth_backends.MongoEngineAuthBackend',
        'accounts.auth_backends.SafeModelBackend',  # Safe SQL backend that handles ObjectIds
    ]
    
    # Use custom session serializer for MongoDB ObjectId
    SESSION_SERIALIZER = 'accounts.session_serializers.MongoJSONSerializer'
    
else:
    # SQLite (default for development/testing)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    
    AUTHENTICATION_BACKENDS = [
        'django.contrib.auth.backends.ModelBackend',
    ]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Required for `collectstatic`
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Only include theme/static if it exists (for development)
STATICFILES_DIRS = []
theme_static_dir = BASE_DIR / 'theme' / 'static'
if theme_static_dir.exists():
    STATICFILES_DIRS.append(theme_static_dir)

# WhiteNoise configuration for serving static files in production
# Use StaticFilesStorage instead of CompressedManifestStaticFilesStorage to avoid manifest issues
if not DEBUG:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.UserProfile'

LOGIN_REDIRECT_URL = 'role_redirect'
LOGOUT_REDIRECT_URL = 'home'

# Keep users signed in during development.
# If you want "log out when browser closes", set SESSION_EXPIRE_AT_BROWSER_CLOSE = True.
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days

# CSRF Settings for development
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF cookie if needed
CSRF_COOKIE_SAMESITE = 'Lax'  # Less restrictive for development
# Allow localhost and .onrender.com domains
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
] + [origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]

# Automatically add Render domain to CSRF trusted origins
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Add Render domains explicitly
if not DEBUG or os.getenv('RENDER'):
    CSRF_TRUSTED_ORIGINS.extend([
        'https://allflex.onrender.com',
        'https://*.onrender.com',
    ])

CSRF_USE_SESSIONS = False  # Use cookie-based CSRF (default, more reliable)

# Session cookie settings
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True

# Tailwind CSS configuration
TAILWIND_APP_NAME = 'theme'
NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"

# Google Gemini API Key for gym recommendations
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', 'YOUR_API_KEY_HERE')

# Email Configuration (Development - Console Backend)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@allflex.com'

# For production, use SMTP:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
# EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
